vocab:
  type: Hierarchy_Vocab
  path:
    train: datasets/Wikilingual-dataset/train.json
    dev: datasets/Wikilingual-dataset/dev.json
    test: datasets/Wikilingual-dataset/test.json
  min_freq: 3
  bos_token: <bos>
  eos_token: <eos>
  unk_token: <unk>
  pad_token: <pad>
  max_words: 60
  max_sentences: 20

dataset:
  train: 
    type: TextSumDatasetHierarchy
    path: datasets/Wikilingual-dataset/train.json
  dev:
    type: TextSumDatasetHierarchy
    path: datasets/Wikilingual-dataset/dev.json
  test: 
    type: TextSumDatasetHierarchy
    path: datasets/Wikilingual-dataset/test.json
  batch_size: 32
  num_workers: 16

model:
  name: Hierachy_Transformer_Wikilingual
  architecture: Hierachy_Transformer
  max_sentences: 20
  d_model: 512 
  n_layers: 6
  n_head: 8
  dropout: 0.1
  device: cpu

training:
  checkpoint_path: "checkpoints"
  learning_rate: 0.15
  lr_coverage: 0.15
  warmup: 1000
  patience: 5
  score: rouge-L

task: TextSumTaskHierarchy