vocab:
  type: MTVocab
  TOKENIZER: null
  bos_token: <bos>
  eos_token: <eos>
  unk_token: <unk>
  pad_token: <pad>

  vietnamese: 
    path:
      train: datasets/PhoMT/train.json
      dev: datasets/PhoMT/dev.json
      test: datasets/PhoMT/test.json
  english: 
    path: 
      train: datasets/PhoMT/train.json
      dev: datasets/PhoMT/dev.json
      test: datasets/PhoMT/test.json
    min_freq: 3

dataset:
  train: 
    type: MachineTranslationDataset
    path: datasets/Wikilingual-dataset/train.json
  dev:
    type: MachineTranslationDataset
    path: datasets/Wikilingual-dataset/dev.json
  test: 
    type: MachineTranslationDataset
    path: datasets/Wikilingual-dataset/test.json
  batch_size: 4
  num_workers: 10

model:
  name: LSTM_Model3layer_MT_Wikilingual
  architecture: LSTM_Model3layer_MT
  d_model: 512
  encoder:
    layer_dim: 3 #LSTM 3 layers
    input_dim: 512
    hidden_size: 512
    bidirectional: False
    dropout: 0.1
  decoder:
    layer_dim: 3
    input_dim: 512
    hidden_size: 512
    bidirectional: False
    dropout: 0.1
  label_smoothing: 0.1
  device: cuda

training:
  learning_rate: 0.15
  warmup: 1000
  patience: 5
  score: BLEU-4
  checkpoint_path: "checkpoints"
  seed: 42  

task: MachineTranslationTask



  